apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pgo236no4-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:cc5f89b938e6eae4a77f47bf44668c9c9151cc2c@sha256:77427ad079b06e5146582c5ddc8a156bce11690e4e01bd85758247b2a203ffbf
          name: container-image
